default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: <%= ENV["DATABASE_PASSWORD"] %>
  timeout: 5000

development:
  <<: *default
  database: voca_development

test:
  <<: *default
  database: voca_test
